### ISSUE TITLE
Overlapping search boxes

### ISSUE THREAD

**Issue by taldcroft** [sot/proseco#10]
In the following catalog (obsid 19778 in APR2318A) there is a big overlap between search boxes for idx=5, 10.  Even a small maneuver error could put the brighter star into box 10.

![image](https://user-images.githubusercontent.com/348089/41158293-67c3bb0a-6af6-11e8-8692-665af6e530a5.png)

I believe from historical precedent that this is OK, but am not entirely sure that the PEA will always assign stars to slots correctly in the event of an unfortunate maneuver error

**Comment by jeanconn** [comment]
Should we use the test set for some checking on these corner cases?  My impression (somewhat from the search box anomaly) is that if the bright star is in both boxes, it will probably get assigned to the box that completes search (has all binned rows read) first.  But that is just an impression.

**Comment by taldcroft** [comment]
Current proseco won't allow overlaps like this where there is ambiguity.  The fainter one idx=10 would get a smaller box to reflect that it can be spoiled by idx=5.  Thus with PEA acq set to pick the brightest star in the box, idx=5 will always get the bright star and idx=10 will always get the faint star (since the bright one can't be in its box).  Here's what it did (80" for brighter and 100" for fainter).

![image](https://user-images.githubusercontent.com/348089/44262322-a0610e80-a1e8-11e8-8366-4a943e41b59e.png)

I would rather that it used 100" and 80" respectively, but I think the probability difference is not large enough to have flipped the two.

In practice if was a problem getting a catalog because a large man angle demanded large boxes, then we would use creep up and away.
