### ISSUE TITLE
Get dense and sparse corner case attitudes for validation

### ISSUE THREAD

**Issue by taldcroft** [sot/proseco#100]
For proseco validation we need dense and sparse corner case catalogs.  Let's say we want the most extreme 10 of each, where they need to be spatially independent (separated by at least 2 degrees radially).  The density can be via one of two metrics: 
- Total number of stars in a 1-deg radius circle (in the miniagasc)
- Number of stars brighter than 10.3 mag (in 1-deg radius)
So that will be 40 attitudes.  No need to worry that the ACA FOV is square for this purpose.

There is precedent for this in `/proj/sot/ska/analysis/star_density_maps` (which is a  more-descriptively named link to Jean's original work in Perl).  But I think it's just as easy to start over in Python for this project.

```
import acis_taco
from Ska.quatutil import eci2radec
eci, area = acis_taco.sphere_grid(n_points, open_angle=179 * np.pi / 180)
n_points = 2000  # More like 40000 for production
eci, area = acis_taco.sphere_grid(n_points, open_angle=179 * np.pi / 180)
ras, decs = eci2radec(eci.transpose())
plt.plot(ra, dec, '.')

for mag_limit in (10.3, 20):
    for ra, dec, in zip(ras, decs):
        # Getting stars should take around 0.1 to 0.2 secs each.
        stars = agasc.get_agasc_cone(ra, dec, radius=1.0)
        # Do filtering and counting, etc

# Make a table with an `n_stars` column and sort by that column

# Start from the most dense and pick ra, dec pairs, making sure that the selected
# one is at least 2 degrees from any previously selected positions.
# Do the same for ordering by sparsest.
```
Assigning to @malgosias, with a goal of completion by Monday night.

**Comment by malgosias** [comment]
Why do we need mag limit of 20 in ``for mag_limit in (10.3, 20)``?

**Comment by taldcroft** [comment]
Just to have some number for the compare.  But basically that is no limit.

**Comment by taldcroft** [comment]
Closed by https://github.com/sot/skanb/pull/32
