### ISSUE TITLE
What should we do with stars with VAR flags set in the AGASC?

### ISSUE THREAD

**Issue by jeanconn** [sot/proseco#11]

**Comment by jeanconn** [comment]
These are the VAR flags in 1.6.  My suggestion (doing no investigation on this) would be to exclude stars from selection if they VAR set to 2 or 4.

```
2    VAR - short integer code providing information on known or suspected
    variable stars.     Default value of -9999.
        1 - suspected variable, with a suspected amplitude variation < 2 mag
        2 - suspected variable, with a suspected amplitude variation > 2 mag
        3 - known variable, with an amplitude variation > 0.2 mag
        4 - known variable, with large amplitude ( > 2 mag), for which an
            ephemeris was necessary
        5 - known variable, with an amplitude variation < 0.2 mag
```

**Comment by taldcroft** [comment]
It depends heavily on whether the MAG_ACA_ERR is reflective of the uncertainty.  If a star can vary by +/- 1.9 mag but has a 0.05 MAG_ACA_ERR then it shouldn't be used.  Without more investigation I'd say the only acceptable var code is 5.

**Comment by jeanconn** [comment]
Before we go that way, we might want to check to see how many otherwise-good stars are labeled with VAR=1.  I don't know how loosely the "suspected variable" has been applied.
