### ISSUE TITLE
exception handling doesn't work for early exceptions on obsid

### ISSUE THREAD

**Issue by jeanconn** [sot/proseco#133]
Looks like the plain string obsid will just break things early at this point before raise_exc is defined (this is now expecting starcheck text with OBSID, but I don't think it was configured that way at 1.0 release) .  IIRC if all the rest of arguments were previously supplied the obsid was basically ignored, which is why I'm supplying it on the matlab side in the prosecoWrite function.  I thought other parts of the pickling were actually breaking before if obsid was null, but maybe that is all historical.

```
In [12]: get_aca_catalog(obsid='20612')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/proj/sot/ska/jeanproj/git/proseco/proseco/core.py in get_kwargs_from_starcheck_text(obs_text)
   1063     try:
-> 1064         kw['obsid'] = int(re.search("OBSID:\s(\d+).*", obs_text).group(1))
   1065     except:

AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/proj/sot/ska/jeanproj/git/proseco/proseco/catalog.py in get_aca_catalog(obsid, **kwargs)
     50         if isinstance(obsid, str):
---> 51             kw = get_kwargs_from_starcheck_text(obsid)
     52             obsid = kw.pop('obsid')

/proj/sot/ska/jeanproj/git/proseco/proseco/core.py in get_kwargs_from_starcheck_text(obs_text)
   1066         # Nothing else will work so raise an exception
-> 1067         raise ValueError('text does not have OBSID: <obsid>, does not look like appropriate text')
   1068 

ValueError: text does not have OBSID: <obsid>, does not look like appropriate text

During handling of the above exception, another exception occurred:

UnboundLocalError                         Traceback (most recent call last)
<ipython-input-12-fee21cb06ed0> in <module>()
----> 1 get_aca_catalog(obsid='20612')

/proj/sot/ska/jeanproj/git/proseco/proseco/catalog.py in get_aca_catalog(obsid, **kwargs)
     60 
     61     except Exception:
---> 62         if raise_exc:
     63             # This is for debugging
     64             raise

UnboundLocalError: local variable 'raise_exc' referenced before assignment
```

**Comment by taldcroft** [comment]
Can you not supply obsid as a string (i.e. use float)?  I'll note that the documentation does specify the API that if obsid is a string then it must be starcheck content as text.

**Comment by taldcroft** [comment]
Obsid has a default of 0 if not supplied, so all should be well.  That's new with the MetaAttribute stuff.  So I suspect that on the Matlab side you might be better off not providing it to `get_aca_catalog`.  But I have very little insight into that code.

**Comment by taldcroft** [comment]
> Not sure what "can you not supply obsid as a string (i.e. use float)? means. Do you want me to supply the obsid to get_aca_catalog wrapped in a float?

I think that if obsid is *anything* but a `str` and you provide all necessary parameters, then the get_starcheck machinery won't be used, and no downstream errors will occur (except possibly with `to_pickle`).  Of course I haven't verified because the assumption has really been that obsid is an `int`.
