### ISSUE TITLE
Review of starcheck evaluation of catalogs

### ISSUE THREAD

**Issue by taldcroft** [sot/proseco#15]
### APR3018A
- [x] 20603: idx=11 is a 10.503 mag star that gets a 160" box despite 4 other 160s.  Seems like smaller would be better.  *Looking at detailed report this looks odd and definitely needs more investigation.*  **Fixed by #32**.

### JUL0218A
- No issues

### JUN0418A
- 49214: Fewer than 3 ACQ stars with 160 boxes ==> **OK**
- [x] 49211: WARNING: [10] Search Box Size. Star too faint for > 120 box => **OK** but I wonder why a smaller box isn't better here.  Same 20433 in MAY0718A.  **OK**

### JUN1118A
- [x] 49199: two overlapping stars / boxes. Probably OK (best possible) but review.  This is actually a very good example of making the best of a difficult field. https://icxc.cfa.harvard.edu/aspect/analysis/proseco/test_loads/JUN1118A/starcheck.html#obsid49199
- [x] 20351: 140 arcsec search box for 10.268 mag star seems non-ideal.  **OK**

### JUN2318A
- 21122: nice example of teeny box right on the edge.

### MAY0718A
- [x] 19403: [10] is 60 arcsec presumably because of the edge.  Same story in 19653, 20181.  Not clear if the probability model is doing the right thing here.  Fraction of box off the edge needs to account for `manvr_err`.  Fixed by #18.

### MAY1418A
- [x] 49252, 49247, 49242: significantly overlapping search boxes with basically identical mags.  50/50 that we get neither (swapped boxes)?  There are no better stars, SAUSAGE went with 60" box on one and a hail mary 10.5 mag star.  **Review**: proseco is doing the best possible here, and correctly assigns these stars with basically 50% on each.

### MAY2118A
- No new issues.

**Comment by jeanconn** [comment]
Several catalogs have Angle Too Large warnings that suggest that the CCD boundaries should be confirmed if we want to push stuff out to the edge.  I opened a new issue #17 for this as well, though I'm not sure about the best way to actually check the useful edges.

**Comment by jeanconn** [comment]
It's a known issue, but we should probably also track the 

  [ ] Fid light in search box

issue somewhere as something that will need to be double-checked on the Matlab side.

**Comment by taldcroft** [comment]
Closing, will open a new one for final validation testing.
