### ISSUE TITLE
Review starcheck catalog outputs

### ISSUE THREAD

**Issue by taldcroft** [sot/proseco#161]
In the proseco project page there are links to starcheck outputs for 10 weekly loads that have been mocked to include proseco-generated catalogs.  Review and note any anomalies.

Known issues:
- Fid light commanding is not updated, so starcheck warns about many fid catalogs.  Ignore.
- Angle too large warning is acceptable for now.
- Nearby bad pixel warning is acceptable for now.

**Comment by taldcroft** [comment]
Jean, Eric, and Tom reviewed starcheck 12.1 outputs for 10 weekly loads and the only actionable comment is captured in #206.  See email thread subject:"Proseco ACA review" for details.

**Comment by jeanconn** [comment]
I thought my comments on color1=0.700 stars may be actionable in the same way (as in not easily).
