### ISSUE TITLE
Handling bad pixel check in starcheck

### ISSUE THREAD

**Issue by taldcroft** [sot/proseco#163]
From #139:

And we foresaw the issue that we're using different definitions of bad pixels at this point. I think for starcheck it makes sense to reimplement the "single bad pixel in region" check with a relative mag threshold equivalent to something like 10.3 mags : 2000 e-/sec . Or reimplement it with the 2x2 bins (I could go either way on what we consider more conservative). Could also chuck the bad pixel detection altogether I think if we run annie-lite on all observations in review.

**Comment by taldcroft** [comment]
I think the 10.3 mags : 2000 e-/sec is a fine starting point if annie-lite doesn't fly.  This would probably then be a green warning.

**Comment by jeanconn** [comment]
At which point would we escalate to orange or red warnings?

**Comment by taldcroft** [comment]
Thking some more, at some level my inclination is to test the heck out of proseco, particularly with units tests having clean well-defined inputs (entirely synthetic data), and prove categorically that it implements the intended response to hot pixels.  Same with large angles.

Then don't do any corresponding checks in starcheck.  I.e. proseco is taken as the definitive reference for hot pixel handling (or allowed CCD angle for acq).  Otherwise you end up with a mismatch between the testing and the expected handling because the starcheck check is always a crude approximation for the reference behavior.  This winds up producing false positives that we just learn to ignore.

I guess you can put in some sanity checks.  If a 20000 e-/sec hot pixel is on top of a 10.3 mag star, that is wrong.  If a star is 50 pixels outside the FOV that is wrong.  But if we have a finite time for development, I think it is better to devote that to writing more (exact) tests on the front end than to develop (approximate) proxy tests on the back end.  This can prove that proseco cannot put a 20000 e-/sec hot pixel on a 10.3 mag star.

And of course the difference now is that we control both the front and back end.

**Comment by jeanconn** [comment]
I think we need more than a "sanity check" to verify that manually selected stars (if any) are reasonable.

**Comment by jeanconn** [comment]
My vision is still that the starcheck should be an independent backstop on selecting a safe catalog, and that the "crude approximations" won't be that bad.

**Comment by taldcroft** [comment]
I was figuring you'd say something like that.  So I probably won't be much help on algorithms then, you'll have to work it out on your own.  

The good news is that we have 12 test catalogs, so I'd like to see zero false positives for red warnings, and very few new (proseco-related) false-positive orange warnings.

**Comment by taldcroft** [comment]
Remilestone to starcheck 13.1

**Comment by jeanconn** [comment]
Well, we've got something now in the starcheck 13.0, so I think this can get closed as a proseco issue.
