### ISSUE TITLE
temperature to use for acquisition

### ISSUE THREAD

**Issue by jeanconn** [sot/proseco#172]
We've set up the matlab tools to feed the expected temperatures at the beginning of the observation to use both for the acquisition catalog determination and the thumbs_up.  I'm wondering just now if we should be more conservative and use the max temperature over the observation.

I'm specifically thing about the "what if we need to reacquire stars" during the observation scenario.  Do we need the "thumbs_up" on acquisition to have margin for this?  Or is that overly conservative thinking (the chances of needing to do a full re-acquisition are small)?

**Comment by jeanconn** [comment]
This is also a question for starcheck review now and as we move to proseco (what temperature should really be used for evaluating acq probability)?

**Comment by taldcroft** [comment]
Yes, too conservative since full re-acqs are very rare now.  You don't want to always plan to the 99.9% outlier for this probabilistic approach.

**Comment by jeanconn** [comment]
Understood and agreed.  Just a little concerned about what we're going to see if the schedule are all planned to get the "time of acquisition" under the planning limit but the Kalman intervals are much warmer than that.
