### ISSUE TITLE
Looks like there are still include/exclude_ids that need _acqs postfix

### ISSUE THREAD

**Issue by jeanconn** [sot/proseco#178]
https://github.com/sot/proseco/blob/1c14d0e1926aa105aa243b72ec3606d9bb7794ea/proseco/acq.py#L46

**Comment by jeanconn** [comment]
Also, what is supposed to happen if exclude_ids is supplied?  

https://github.com/sot/proseco/blob/1c14d0e1926aa105aa243b72ec3606d9bb7794ea/proseco/tests/test_catalog.py#L39

I would have thought that would be an error as an undefined kwarg at this point.

**Comment by taldcroft** [comment]
The API is that the sub-selectors (acq, guide) use `include_ids` or `exclude_ids` while `get_aca_catalog` uses the `acq` or `guide` postfix.

The way it works now is that if you provide `exclude_ids` it gets applied to both `acq` and `guide`.  That can be seen as a feature that needs documentation or a bug.  Likewise for `dither` or `t_ccd`.
```
In [1]: from proseco import *
In [2]: aca = get_aca_catalog(21007, t_ccd=-10, dither=(8,8))
In [3]: aca.guides.t_ccd
Out[3]: -10
```

**Comment by taldcroft** [comment]
For testing, I put in a comment in #176 suggesting to revert the 20603 test to use `exclude_ids` and make sure the guide star is excluded.  I would consider that enough of a test for this feature that is not really intended for general use.

In fact I think I'll backtrack a little on my "needs documentation" comment and consider this usage to be not part of the public API.  So I'll add a comment to the code but not the docstring.

**Comment by taldcroft** [comment]
Is #180 good enough to close this now?

**Comment by jeanconn** [comment]
Sure.
