### ISSUE TITLE
Confirm CCD extent allowed for guide

### ISSUE THREAD

**Issue by jeanconn** [sot/proseco#191]
In the context of obsid 21277 in DEC0318 confirm that star 1154748456 is in bounds.

The starcheck boundary tests look like they should basically match the proseco guide check for outofbounds,

https://github.com/sot/proseco/blob/52145e0993239c55dd40d75046d9f6c4ce9a8b57/proseco/guide.py#L317

https://github.com/sot/starcheck/blob/d187813388b559426169ffe9d78ead43534dd342/starcheck/src/lib/Ska/Starcheck/Obsid.pm#L1334

 so not immediately clear about the Angle Too Large warning from starcheck.

**Comment by jeanconn** [comment]
For 21277 in this test, it looks like starcheck has dither = 20 because of no dither continuity.  If we get to use kadi for continuity for proseco starcheck this goes away.
Also, starcheck wants ATTITUDE.txt now (not in the starcheck proseco outputs now) but that can also be set for kadi dynamic states.

**Comment by taldcroft** [comment]
Seems like this can be closed since the original issue is understood.

**Comment by jeanconn** [comment]
That's fine.  I still don't know if the edges are right, because we're using pads and such that don't seem to have defined sources

https://github.com/sot/proseco/blob/bb3bc560a53d83333914090cc3216e340b1e7aff/proseco/characteristics.py#L8

I haven't, for example, tried to dig out stars dithering off the CCD in telemetry.  But the boundaries seems reasonable given mission experience.

**Comment by jeanconn** [comment]
Actually, do we want to find some some very-edge tracking data or some such for the presentation anyway?  We are allowing guide stars farther out than SAUSAGE selection and then are planning to change starcheck to agree on the new edges, so it seems to me this algorithm change needs justification somewhere.
