### ISSUE TITLE
Guide star selection: pixel region not calculated correctly for asymmetric dither

### ISSUE THREAD

**Issue by jeanconn** [sot/proseco#194]
These bits in this subroutine should reference "extent" not "row_extent"

https://github.com/sot/proseco/blob/52145e0993239c55dd40d75046d9f6c4ce9a8b57/proseco/guide.py#L622

**Comment by jeanconn** [comment]
@taldcroft This is a small population of observations, but I think this should be patched and re-released.

**Comment by taldcroft** [comment]
Agreed.  The only question is about patch release schedule, if we are releasing for each bug or waiting to see if others are found.
