### ISSUE TITLE
Guide star selection tracks imposter mag, but is 'inf' for 0 dark current

### ISSUE THREAD

**Issue by jeanconn** [sot/proseco#196]
For constructed cases the dark map region set to, the count_rate_to_mag(0) gives warning and mag of inf.  Is there value in that or should we set the mag to a non-inf value and get rid of the warning?

**Comment by jeanconn** [comment]
@taldcroft Did you have thoughts on this for the patch release?

**Comment by jeanconn** [comment]
I just set the minimum mag to 20.0 in the end of #195 to avoid all the warnings for the new tests of the fixed extent.  If a larger numeric would be appropriate or if "inf" is fine but should get set without a warning, let me know.

**Comment by taldcroft** [comment]
Yes on getting this fixed for 4.3.1.
