### ISSUE TITLE
Improve guide tests

### ISSUE THREAD

**Issue by taldcroft** [sot/proseco#203]
- Docstrings for every test
- Common column synthetic
- Etc.

**Comment by jeanconn** [comment]
I've reviewed the tests and threw a bunch of time at trying to come up with more synthetic tests for the untested areas but I can't figure out anything that works.

There are two places where we have limited/poor coverage:

1) the star spoils another star by integrated light falling unto its 8x8 or by light falling unto its background pixel region.  I can't figure out tests that don't reimplement the code itself.

2) for the bad pixel check I run into the same issue.  I can't figure out synthetic tests that don't reimplement the code.

**Comment by jeanconn** [comment]
For 2) I can easily add one more synthetic case where we "know" the answers and hardcode them in the test.  That's the level of coverage we currently have for 1).

**Comment by taldcroft** [comment]
For (1) you don't need perfect, just good.  So for instance the following would give a visual sanity check that it is doing about the right thing and a hardcoded regression test that future code updates don't break it.
```
drcs = np.arange(10)
selected = []
for drc in drcs:
    # Add star at row, col = 10, 10
    # Add spoiler star 3 mags fainter at row, col = 10 + drc, 10 (integrated light test)
    selected.append((star was selected).astype(int))
# Look at result and confirm that it makes sense (in particular is it selected with drc=0?)
# Hard code that result and then it is a regression test.
# You could probably do this for dmag=1 and 2 mags if that shows anything different or interesting
```
Do the same thing again but with `row, col = 10 + drc, 10 + drc (background pixels test)`

**Comment by jeanconn** [comment]
For 1) I thought the test you are describing is basically the one (two) that is (are) there:

https://github.com/sot/proseco/blob/086407e0c6ef08abb56aada0615d516b25157d58/proseco/tests/test_guide.py#L186

**Comment by taldcroft** [comment]
A hard-coded set of values for each case like `[0, 0, 1, 1, 1, 1, 0, 0, 0, 0]` is compact, easy to visualize and easy enough to maintain.   In fact you could even use 0.5 pixel spacing (for 20 cases) and stack 3 mag cases into a single array to get something resembling a text image of the results.

The difference with the existing test is that covers a grid of cases and also exercises the full star selection machinery so tests that `check_spoil_contrib` is in fact being called as expected.

I would not expect these tests to change unless we actually change the algorithm, in which case the maintenance is the right thing.

**Comment by jeanconn** [comment]
Oh.  I implemented it as a check_spoil_contrib case which is not exercising the full star selection machinery.

**Comment by jeanconn** [comment]
I thought isolated was better than full machinery testing for this stuff but will revise.

**Comment by jeanconn** [comment]
The issue with using the full machinery is that `check_spoil_contrib` and  `has_spoiler_in_box` and `check_mag_spoilers` all overlap.  So if we're fine with the gridded test you suggest just being a generic spoiler test blind to which test marked it as a spoiler, that's fine.
