### ISSUE TITLE
Cannot include bad guide star 75503864 in obsid 21004

### ISSUE THREAD

**Issue by taldcroft** [sot/proseco#204]
This is a lousy guide star we would never select, but force include should still be accepted.  Acq is OK, but for guide it raises an exception:
```
In [45]: aca = get_aca_catalog(21004, include_ids_guide=75503864)

In [46]: print(aca.exception)
Traceback (most recent call last):
  File "/Users/aldcroft/anaconda3/envs/ska3/lib/python3.6/site-packages/proseco/guide.py", line 279, in process_include_ids
    raise ValueError("Not a valid candidate")
ValueError: Not a valid candidate

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aldcroft/anaconda3/envs/ska3/lib/python3.6/site-packages/proseco/catalog.py", line 69, in get_aca_catalog
    aca = _get_aca_catalog(obsid=obsid, raise_exc=raise_exc, **kwargs)
  File "/Users/aldcroft/anaconda3/envs/ska3/lib/python3.6/site-packages/proseco/catalog.py", line 111, in _get_aca_catalog
    aca.guides = get_guide_catalog(stars=stars, fids=aca.fids, **kwargs)
  File "/Users/aldcroft/anaconda3/envs/ska3/lib/python3.6/site-packages/proseco/guide.py", line 48, in get_guide_catalog
    guides.cand_guides = guides.get_initial_guide_candidates()
  File "/Users/aldcroft/anaconda3/envs/ska3/lib/python3.6/site-packages/proseco/guide.py", line 364, in get_initial_guide_candidates
    self.process_include_ids(cand_guides, stars)
  File "/Users/aldcroft/anaconda3/envs/ska3/lib/python3.6/site-packages/proseco/guide.py", line 281, in process_include_ids
    raise ValueError(f'cannot include star id={include_id} that is not '
ValueError: cannot include star id=75503864 that is not a valid star in the ACA field of view


In [47]: aca = get_aca_catalog(21004, include_ids_acq=75503864, include_halfws_acq=60)

In [48]: aca
Out[48]: 
<ACATable length=11>
 slot  idx     id    type  sz   p_acq    mag    maxmag   yang     zang    dim   res  halfw
int64 int64  int64   str3 str3 float64 float64 float64 float64  float64  int64 int64 int64
----- ----- -------- ---- ---- ------- ------- ------- -------- -------- ----- ----- -----
    0     1        3  FID  8x8   0.000    7.00    8.00    40.01 -1871.10     1     1    25
    1     2        5  FID  8x8   0.000    7.00    8.00 -1826.28   160.17     1     1    25
    2     3        6  FID  8x8   0.000    7.00    8.00   388.59   803.75     1     1    25
    3     4 75498256  BOT  6x6   0.954    9.39   10.89  1347.90   657.87    20     1   160
    4     5 75500368  BOT  6x6   0.968    9.15   10.65  -944.45  1120.33    20     1   160
    5     6 75501776  BOT  6x6   0.960    9.31   10.81  -591.78  1725.80    20     1   160
    6     7 75890912  BOT  6x6   0.970    9.10   10.60   952.71 -1788.02    20     1   160
    7     8 75892688  BOT  6x6   0.981    7.94    9.44  -304.99 -2134.88    20     1   160
    0     9 75894264  ACQ  6x6   0.921    9.74   11.24  2103.27 -1542.80    20     1   160
    1    10 75501240  ACQ  6x6   0.922    9.78   11.28  -802.92  -642.60    20     1   120
    2    11 75503864  ACQ  6x6   0.062   10.95   12.45    55.30    47.10    20     1    60
```

**Comment by jeanconn** [comment]
It is a class 1 star. 
For force include I thought we agreed on the minimum requirements, which were class==0 and on the useable CCD for a guide star:

https://github.com/sot/proseco/blob/bb3bc560a53d83333914090cc3216e340b1e7aff/proseco/guide.py#L279

**Comment by jeanconn** [comment]
I'm more concerned about p_acq for the class=1 star...

**Comment by taldcroft** [comment]
Manual include should allow whatever the user wants (with the stipulation that off the CCD is clearly never acceptable).  We might have other information (from a different catalog or all-sky-survey imaging for instance) that says the class=1 star is actually OK.

**Comment by jeanconn** [comment]
OK, so I guess we didn't agree on class==0 being a minimum requirement for include/exclude.  I was under the impression if you wanted to do something crazy that's what the pure manual edit was for. 

Anyway this code block is also currently testing that the included stars is on the useable part of the CCD with dither and padding.  If we are removing what I considered the minimum requirements we could also bump the out the CCD region to be all of the possible CCD.

**Comment by taldcroft** [comment]
So while we're at it, the guide process_include_ids should be just the same as acq and let anything that is in `stars` be included.  This follows the ORviewer philosophy that a manual edit (aka include) let's you do what you want, but we know that load review will catch it.

https://github.com/sot/proseco/blob/bb3bc560a53d83333914090cc3216e340b1e7aff/proseco/acq.py#L424

Doing it this way is nice because we can remove duplicated code and use a base class `process_include_ids` method.  The acq version will require some additional processing before calling `super().process_include_ids(..)`.  We'll just change `acq`/`guide` to `star` for the generic handling.

I can do this, I love refactoring and deleting code.

**Comment by jeanconn** [comment]
OK.  Though I thought at least the "on the useable FOV for guide stars" was actually value added in this case.  If FOT MP tries to use an include_id star for a set of observations at different rolls, and one places the star just a bit too far out for guide use, just blindly including the star may not be as helpful as returning an empty catalog and requiring a change.

Blindly including an off-the-FOV-for-guide star  would also require that it be removed from the thumbs_up calculation etc.

**Comment by jeanconn** [comment]
If you wanted to backport bugfixes to 4.3.x @taldcroft  I note that this bug (and probably others?) would be open.

**Comment by jeanconn** [comment]
I think I reopened this if we needed it for backports, but based on https://github.com/sot/sparkles/issues/132 as a recent check, proseco will let me add whatever.
