### ISSUE TITLE
Is dither handled correctly?

### ISSUE THREAD

**Issue by jeanconn** [sot/proseco#22]
I had two questions about dither that I articulated poorly at the SSAWG. When I was talking about the placement of the box on the CCD with regard to dither I was really asking:

1) Is dither appropriately accounted for when extracting a CCD region to look for bad pixels?

The answer to this is yes.  The CCD region for the star includes padding for dither in the pixels that "could" be read out by the PEA when trying to get the star. 

https://github.com/sot/proseco/blob/8b16230e29cfa17602e198c9553c4795f19db669/proseco/acq.py#L677

The other question was:

2) Does the dither get into the acquisition probability (for edge stars) in a way that makes sense?

The answer is that it looks right to me, in that the "box" idea for the probability that the star will be on the CCD uses the dither:
https://github.com/sot/proseco/blob/8b16230e29cfa17602e198c9553c4795f19db669/proseco/acq.py#L833

3) Do we need to care about dither with regard to where the star is in the box in relation to hot pixels (intruders)?

No.  For acquisition the PEA is just trying to track the brightest thing in the search box, so the approach that you just need to calculate the probability that the star is the brightest thing in the box (compared to other stars and hot pixels) seems reasonable:

https://github.com/sot/proseco/blob/8b16230e29cfa17602e198c9553c4795f19db669/proseco/acq.py#L689

**Comment by taldcroft** [comment]
Yay, thanks for the independent check.  This code has a lot of knobs so this is very useful.
