### ISSUE TITLE
Guide star selection validation

### ISSUE THREAD

**Issue by jeanconn** [sot/proseco#223]
I don't recall where this issue ended up, but I put up some validation in

https://nbviewer.jupyter.org/url/cxc.harvard.edu/mta/ASPECT/proseco/proseco_4.3.1_guide_review.ipynb?flush_cache=true

**Comment by jeanconn** [comment]
This is now updated in:
https://nbviewer.jupyter.org/url/cxc.harvard.edu/mta/ASPECT/proseco/validation-guide-4.3.3.ipynb

**Comment by taldcroft** [comment]
The validation notebook is complete.
