### ISSUE TITLE
Improve guide validation plots of n_stars

### ISSUE THREAD

**Issue by taldcroft** [sot/proseco#231]
Since `n_stars` is a continuous fractional value, you can plot the histogram (cell 92) with `bins=50` or so.  You can also plot a scatter plot of `n_n_stars` vs `o_n_stars` and a histogram of the difference `n_n_stars - o_n_stars` to see if they look nice.

**Comment by jeanconn** [comment]
With regard to the histogram, the value still isn't showing a *lot* for the metric or proseco with more bins?

![n_star_more_bins](https://user-images.githubusercontent.com/791508/50812922-a57f4100-12e2-11e9-8447-2e7619aeb5c1.png)

**Comment by taldcroft** [comment]
Well looks a little better.

**Comment by jeanconn** [comment]
I read it as
SAUSAGE wasn't doing a bad job on guide stars and most observations had "5" bright guide stars.  For observations in star-constrained fields, relaxing some requirements (ASPQ1 / spoiler) helps to get some brighter candidates.  But you are also excluding more based on local dark map.  Then you have a couple of 3.0 outliers because their as-run catalogs used stars fainter than 10.3 .  Those are still "worth points" via n_stars but are not presently selectable in proseco guide.

**Comment by taldcroft** [comment]
About the 3.0 outlier, then I don't understand why there is not a SAUSAGE point at 3.0 + some fractional value.  I.e. the as-run must have at least one or two numbers < 0.5 in the sum due to the mag > 10.3 stars.

BTW, if you find time to remake the plot, use 
```
bs = 0.1
bins=np.arange(3.0 - bs / 2, 5.0 + bs, bs)
```
That will center the bins on integral values.

**Comment by taldcroft** [comment]
The plot appears to show one 3.0 outlier, not a "couple".  ??

**Comment by taldcroft** [comment]
But anyway, thanks for the interpretation of the situation, that will get into the presentation.

**Comment by jeanconn** [comment]
And yes, I misspoke, there are a couple of outliers with proseco catalogs with n_stars less than 4.0, not a couple with n_stars == 3.0.  With regard to their SAUSAGE equivalents, obsid 18460 had two stars with mag > 10.3, so it has a proseco n_stars of 3 and an as-run n_stars of 4.6.  Obsid 19488 had one star in the as-run with mag > 10.3, so has a proseco n_stars of 3.9 and an as-run n_stars of 4.7.  I don't think we want any of that in the validation notebook unless we want to toss a bunch of links to per-obs investigations.

**Comment by taldcroft** [comment]
I'm not following.  A star with (temperature-adjusted) mag > 10.3 is going to have a fractional count < 0.5, and it goes to 0.0 at 10.4.  Both the new star count function and proseco should be using temperature-adjusted mag, so I'm just lost.  The red line below is the one to look at.

![image](https://user-images.githubusercontent.com/348089/50861610-444d8100-1367-11e9-8586-9f089bf25ea4.png)

**Comment by jeanconn** [comment]
What's the question?

**Comment by taldcroft** [comment]
How can obsid 18460 have a star count of 4.6 and proseco only have 3.0, if the only difference between them is two stars fainter than 10.3.  2 * (something less than 0.5) < 1.0, so the SAUSAGE star count should be less than 4.0.

**Comment by taldcroft** [comment]
Also a nit but just another thing I don't understand... if the proseco n_star for 19488 is 3.9 then there should be a distinct bin with a value of 1 at 3.9.  I don't see that.

**Comment by jeanconn** [comment]
OK so maybe I implemented n_stars incorrectly at top?  I'm a bit lost in the temperature adjustments in your comments.

**Comment by jeanconn** [comment]
I was talking about the catalog mags which I was just feeding to the n_stars that I reimplemented (because proseco star selection was changing in master and I was trying to test 4.3.1/2).

**Comment by jeanconn** [comment]
Or is your concern that proseco.guide should have selected the 10.347 star for an observation at -13.2?  I somewhat agree if the local dark map was good, but I don't have temperature-adjusted mag limits in proseco.guide at this point, just the 10.3 hard limit.

**Comment by taldcroft** [comment]
Ah, progress!!  I thought it was using the temperature-adjusted 10.3 mag limit.  That's fine, we now have #235 to ponder (later).

**Comment by jeanconn** [comment]
Great!  And yes, I just went with the 10.3 non-adjusted hard limit we had in SAUSAGE because I didn't think we had enough annie confidence to use to try justify using fainter stars again (and I thought we *might* not be there until dynamic background patch).  But definitely worth more analysis if it will buy us more stars (safely).

**Comment by taldcroft** [comment]
The more realistic flip side is that if we have observations at T_ccd = -7.0 (dynamic limits) then the code is allowing fainter stars than it should...  Not a safety problem since it'll show in starcheck and star count.

Remember the reference temperature is -10.9C and we'll often be warmer than that.

**Comment by jeanconn** [comment]
> The more realistic flip side is that if we have observations at T_ccd = -7.0 (dynamic limits) then the code is allowing fainter stars than it should

Though the hope is that the dark current imposter limit in stage 5 will be enough to keep stars that will be significantly spoiled from being selected.  But the limit is not well tested (probably need a lot more temperature range testing and annie comparisons at those hot temperatures).

**Comment by taldcroft** [comment]
Guide validation plots for the TRR presentation have been improved per the issue description.  Other discussion that came up has been captured in a new issue.  Closing.
