### ISSUE TITLE
Use temperature-adjusted mag for guide star selection filtering

### ISSUE THREAD

**Issue by taldcroft** [sot/proseco#235]
From https://github.com/sot/proseco/issues/231#issuecomment-452475630 and previous, it seems to me that guide selection should be using temperature-adjusted mags in most situations.  In particular counting stars and selecting stars.  

Star evaluation would still use the catalog mag since it gets compared against temperature-adjusted pixels.

**Comment by jeanconn** [comment]
Do we want to do anything with this for 4.4?  It is somewhat the same problem as #259 ; deciding when we are better off with no guide star than a faint or spoiled star.
