### ISSUE TITLE
Effective acq dither incorrect from ORViewer for monitor window observations.

### ISSUE THREAD

**Issue by jeanconn** [sot/proseco#236]
I think that if dither is disabled a minute before the end of the maneuver to the monitor window target, that we should see 0 effective amplitude .    

21191 has a monitor window

```
In [7]: t = pickle.load(open('/data/mpcrit1/mplogs/OFLS_testing/2019/JAN0419/oflst/JAN0419T_proseco.pkl', 'rb'))

In [8]: t['21191'].call_args
Out[8]: 
{'att': <Quat q1=0.19821939 q2=-0.42412821 q3=-0.73323293 q4=0.49314684>,
 'date': '2019:009:06:21:29.739',
 'detector': 'ACIS-S',
 'dither_acq': (7.9992, 7.9992),
 'dither_guide': (7.9992, 7.9992),
 'exclude_ids_acq': array([], dtype=float64),
 'exclude_ids_guide': array([], dtype=float64),
 'focus_offset': 0.0,
 'include_halfws_acq': array([], dtype=float64),
 'include_ids_acq': array([], dtype=float64),
 'include_ids_guide': array([], dtype=float64),
 'man_angle': 93.2239721322994,
 'n_acq': 8,
 'n_fid': 3,
 'n_guide': 4,
 'obsid': 0,
 'sim_offset': 0.0,
 't_ccd_acq': -10.964840380973815,
 't_ccd_guide': -10.81183494157502}
```

**Comment by taldcroft** [comment]
Correct, and I labeled this as Matlab tools.  Given that it just makes acq selection slightly more conservative in a rare circumstance, I would recommend against fixing this upstream.  

@jeanconn - if you agree can you apply `wontfix` and close?

**Comment by jeanconn** [comment]
Thanks, missed the Matlab tag.  

Because I missed this in issue verification and validation, my "priority-low" was a guess on scope (guessing this just applies to monitor window observations).   Since that was still a guess I wasn't sure if we should `wontfix` this without more validation or code review.

**Comment by taldcroft** [comment]
The thing that we need to double-check is that proseco is getting the right dither for big dither observations.  Do you recall which (if any) of the MATLAB test loads had a big dither?

**Comment by jeanconn** [comment]
The AUG2018U schedule had obsid 20168 with big dither.  I think you properly checked in the validation and verification, but for the record:

```
In [2]: t = pickle.load(open('/proj/sot/ska/www/ASPECT/proseco/matlab-proseco-loads/AUG2018U/AUG2018U_proseco.pkl', 'rb'))

In [4]: t['20168'].call_args
Out[4]: 
{'att': <Quat q1=-0.27740613 q2=0.39287273 q3=-0.25319284 q4=0.83939874>,
 'date': '2018:233:07:14:36.349',
 'detector': 'HRC-S',
 'dither_acq': (20.0016, 20.0016),
 'dither_guide': (64.0008, 7.9992),
 'exclude_ids_acq': array([], dtype=float64),
 'exclude_ids_guide': array([], dtype=float64),
 'focus_offset': -70.0,
 'include_halfws_acq': array([], dtype=float64),
 'include_ids_acq': array([], dtype=float64),
 'include_ids_guide': array([], dtype=float64),
 'man_angle': 175.77577229056934,
 'n_acq': 8,
 'n_fid': 3,
 'n_guide': 5,
 'obsid': 0,
 'sim_offset': 0.0,
 't_ccd_acq': -12.392379023393898,
 't_ccd_guide': -12.408771757305466}
```

**Comment by taldcroft** [comment]
Perfect, closing this issue then.

**Comment by taldcroft** [comment]
I also removed the Bug label since I think I *want* to have the larger dither for acq checking in this case.

**Comment by jeanconn** [comment]
Why would you want the larger dither for acq checking in this case?

**Comment by taldcroft** [comment]
The operational requirement for the special monitor window commanding is that the dither is zero at the time of the second guide search when the mon window is acquired.  There is no requirement that dither is zero at the time of acquisition.  So we cannot have that expectation at this point.

**Comment by jeanconn** [comment]
Ah.  OK.  So the effective dither may be something more than zero amplitude one minute after commanded dither disabled.  Fair enough.

**Comment by jeanconn** [comment]
Somewhat in the weeds then, but should starcheck *review* the catalog with zero dither or the dither before it was disabled?
