### ISSUE TITLE
Decide how to check observations with commanded 0 dither during acq

### ISSUE THREAD

**Issue by jeanconn** [sot/proseco#239]
For observations with monitor windows and observations approaching a dark cal, there can be acquisitions during the interval when commanded dither is 0 ampl or dither disable.  Should starcheck us the previous dither (which may be the effective dither at the time of acquisition)?  

For starcheck 13.0 it will be feeding proseco.get_acq_catalog with the commanded dither for these rare special-case observations.

**Comment by jeanconn** [comment]
Oops, this was supposed to be a starcheck issue.

**Comment by taldcroft** [comment]
https://help.github.com/articles/transferring-an-issue-to-another-repository/
