### ISSUE TITLE
Consider changing guide POS_ERR threshold

### ISSUE THREAD

**Issue by taldcroft** [sot/proseco#242]
The current POS_ERR threshold for guide selection allows errors up to 3.0 arcsec.  This is actually quite large and we likely should not use such stars.  Fortunately there are rather few candidate guide stars with position error above 1.0 arcsec, about 0.2% (about 800 of 432k), so 1.0 arcsec might be a natural more conservative limit.

![image](https://user-images.githubusercontent.com/348089/51503023-d3668a00-1da6-11e9-8836-12b27ce51909.png)
The plot above is based on the miniagasc_1p7, filtered by `GuideTable.get_candidates_mask()`.

In the meantime we should put in warnings to `aca_preview`, maybe warning at 1" and critical at 2".

**Comment by jeanconn** [comment]
FOR proseco guide star selection it is another side effect of dropping the figure of merit optimization that we'd be more likely to select one of these stars with larger POS_ERR than the previous algorithm (though it would make no difference in sparse fields).

**Comment by jeanconn** [comment]
Seems fine to just set to hard limit 1.0 arcsec for next release.

**Comment by taldcroft** [comment]
Agreed.
