### ISSUE TITLE
What to do with guide star selection and color=1.5?

### ISSUE THREAD

**Issue by jeanconn** [sot/proseco#243]
I'm not sure how to prioritize perhaps-incorrect mag error on color 1.5 stars.  Not sure if this will go away if we update the AGASC again with GAIA data or if we'll need some more mag error terms in guide star selection.

**Comment by jeanconn** [comment]
@taldcroft Do you want to do anything with color 1.5 stars for this proseco 4.4 (?) release?

**Comment by taldcroft** [comment]
This requires analysis / thought.  You can milestone for 4.4 and see if we have time.

**Comment by jeanconn** [comment]
Also a tough question about how much we want to mess with the guide star stages for this release.   I think #254 (or something like it to not get really-bright stars in the first stages) will have a moderate impact (read=many catalogs with some change). already on overall star selection.

**Comment by jeanconn** [comment]
I think the mag_err = 0.3 stuff that is already in there is fine.

**Comment by taldcroft** [comment]
Agreed.  I'm fine to close this.
