### ISSUE TITLE
API: provide obsid to proseco

### ISSUE THREAD

**Issue by taldcroft** [sot/proseco#256]
In the context of catalog checking (thumbs up) there can be different rules for ORs and ERs.  An obsid is the normal way of differentiating.

Strictly speaking this might be needed only for aca_review, but putting it upstream in the proseco ACA table object would be nice.

**Comment by jeanconn** [comment]
Might want a flag in get_aca_catalog to prevent obsid lookups in mica.starcheck in case of supplied obsid but missing other required parameter.  Operationally we'd prefer error to use of incorrect data.

**Comment by jeanconn** [comment]
@taldcroft Did you think my last comment was too conservative or should we open an issue and implement in proseco.get_aca_catalog?

**Comment by taldcroft** [comment]
I think it is too conservative.  "Operational" calls to `get_aca_catalog` are going to be via code that is verified to supply the required arguments, and by definition will be using obsids that don't already exist in starcheck.db3.  I don't see a really credible path for an accidental call.

Having said that, I think it is reasonable to change the API to disallow the "mixed" inputs case.  Basically you can only get the mica.starcheck backend if *only* obsid is provided.  If any other args are provided then it doesn't go that route.  That makes it slightly harder in our development end but is then quite safe.  I can make a helper function that does what the current code would have done for a mixed "obsid + other kwargs" case, to make it easy to get the necessary kwargs for a subsequent call of `get_aca_catalog(**kwargs)`.

**Comment by jeanconn** [comment]
Forbidding "mixed" input looks to more than satisfy my only cause for concern :+1:

**Comment by taldcroft** [comment]
@jskrist reports that this is now done in ORviewer.

**Comment by jeanconn** [comment]
As part of testing this change, I'll want to review the single exported obsid pickle file and the overall schedule exported pickle file.  Do you want to start a new page for test requirements or the like @taldcroft ?

**Comment by taldcroft** [comment]
I'm just labeling this "testing" now so we don't forget.  I want to focus on development until Tuesday COB.

BTW there is a functional test already because the sparkles HTML reports would show obsid=0 everywhere if the obsid is not being passed correctly.  So yes, good to look for this in the pickle eventually, but extremely unlikely it will fail.

**Comment by jeanconn** [comment]
"BTW there is a functional test already because the sparkles HTML reports would show obsid=0 everywhere if the obsid is not being passed correctly."  Well, there's only a functional test if somebody checks it :+1: .

**Comment by taldcroft** [comment]
I already saw it on the James' screen yesterday.  :smile:

**Comment by jeanconn** [comment]
Great!  When I mentioned the two pickles (single and full schedule), I was also thinking that right now they are each made with a separate code to call proseco with keywords and both calls needs the obsid fix (unless they get combined in the final code).

**Comment by taldcroft** [comment]
This is done now.
