### ISSUE TITLE
man_angle input to proseco is incorrect for an intermediate attitude gyro-hold

### ISSUE THREAD

**Issue by taldcroft** [sot/proseco#266]
Currently the `man_angle` value that gets passed to `get_aca_catalog` in ORviewer reflects only the angle of the maneuver just prior to the attitude for catalog selection.  In the case of a segmented maneuver with a gyro-hold, this is incorrect.

A specific example is obsid 48398 which preceded the Sco X-1 observation 21263 in FEB1819.  Obs 48398 was originally selected using a man_angle of 1.07 deg, but in fact that was coming from a gyro hold that had been preceded by an 84 deg maneuver.

One option is simply summing up the preceding maneuver angles.

**Comment by jeanconn** [comment]
I think this can be closed as I think all the time in maneuver mode is now getting counted in the manuever angle calculation.

There is the super tiny new issue that I don't know if we should try to do something for the case where we've done an acquisition but only 10 second Kalman dwell.  It seems to me without a good bias update that the error on the next maneuver is likely to be worse than after a plain dwell, but maybe that isn't actually true in a statistical sense and is all in the noise.

**Comment by taldcroft** [comment]
Agreed to close.
