### ISSUE TITLE
Use mag history and other useful info from agasc_supplement.h5

### ISSUE THREAD

**Issue by taldcroft** [sot/proseco#276]
Follow on from #272 (and the issue it closed).

**Comment by jeanconn** [comment]
I think this is basically done, though I suppose I should open a new issue to save the agasc versions in the proseco pickle.

**Comment by taldcroft** [comment]
When the day comes that you are annoyed that you don't have the versions, then make the PR. Making the issue now won't really help to get the versions in there. :smile:
