### ISSUE TITLE
Using gzip and protocol=4 in ORviewer

### ISSUE THREAD

**Issue by taldcroft** [sot/proseco#284]
@jskrist - here is what you should do in ORviewer for pickling the catalogs:
```
>>> import pickle
>>> import gzip
>>> from proseco import get_aca_catalog

>>> aca = get_aca_catalog(20603)

>>> pickle.dump(aca, open('aca1.pkl', 'wb'))

>>> with gzip.open('aca1.pkl.gz', 'wb') as fh:
...     pickle.dump(aca, fh, protocol=4)
...     

>>> ls -l aca1.pkl*
-rw-r--r--  1 aldcroft  staff  171939 Feb 20 17:37 aca1.pkl
-rw-r--r--  1 aldcroft  staff   22239 Feb 20 17:37 aca1.pkl.gz

>>> with gzip.open('aca1.pkl.gz', 'rb') as fh:
...     aca1 = pickle.load(fh)
...     
```

**Comment by jeanconn** [comment]
Great.  I'll include this in my interim suggestions for the pickle-write
function (which may or may not be replaced with a call from the new
proseco/sparkles calling code in the next release).

**Comment by jeanconn** [comment]
Oh, as getting the multiline statement will take me more pyexec wrangling, what are the issues with
```
pickle.dump(aca, gzip.open('aca1.pkl.gz', 'wb'), protocol=4)
```
?

**Comment by taldcroft** [comment]
That version basically relies on garbage collection running to finally close the file handle.  I think that in practice it is going to be fine, but not really ideal for production code.

**Comment by taldcroft** [comment]
For a one liner I would prefer:
```
with gzip.open('aca1.pkl.gz', 'wb') as fh: pickle.dump(aca, fh, protocol=4)
```
I *think* this will work.  This is just using deprecated syntax, but solid file handling.

**Comment by jeanconn** [comment]
OK.  I'll either close explicitly, use "with" in multiline, or use your "with" in one-liner.

**Comment by jskrist** [comment]
@jeanconn  -

> Oh, as getting the multiline statement will take me more pyexec wrangling, [...]

I have a MATLAB example script showing various approaches to performing multiline statements with pyexec,  I'll send it your way.

**Comment by jeanconn** [comment]
I think this was done.
