### ISSUE TITLE
Starcheck needs to be able to call to get access to probabilities

### ISSUE THREAD

**Issue by taldcroft** [sot/proseco#3]
There needs to be a pathway for starcheck to feed in a load catalog (which may have been hand-edited) and get the individual star marginalized `p_acq` and probably `p_safe`.  Right now the code assumes the acq catalog has been generated and has the required metadata.

**Comment by jeanconn** [comment]
Can you explain this some more?  I'm not seeing where you are going.

**Comment by taldcroft** [comment]
This is no longer the paradigm, starcheck should just be reading the YAML report (directly or via calls to Python) to get the star `p_acq` values and safing probabilities.  So there is an action on starcheck but this can be closed.

**Comment by jeanconn** [comment]
I'd prefer if starcheck could independently calculate the probabilities on the final catalogs.  This could certainly be done via Python calls to the methods that are used to calculate the marginalized probabilities, but I don't understand why we want to use the proseco YAML report.

Maybe I'm just not understanding the function of the YAML, but the worst case I would see would be that an implementation bug would have a "stale" proseco catalog in final products (determined, say using a stale maneuver angle).  I'd like starcheck to, eventually, be doing the probability calculation using the actual maneuver angle as determined from backstop/DOT, the table of manerr by maneuver angle in your tools, the acq probability model, the temperature, and the star catalog.  

If we check using a YAML file independently created at the time of star selection, we'd both have a new data file dependence in starcheck (which we were trying to avoid) and we'd need code to recheck that all the input pieces used in the report matched the conditions equivalently determined from backstop/DOT.

**Comment by taldcroft** [comment]
BTW, starcheck is going to need the YAML file dependence in any case because this is the input for the HTML report file generation.  I.e. that report is reflecting the SAUSAGE load generation / star selection process, not starcheck.  So starcheck can call proseco in a particular way to re-generate the probabilities, but not to re-create the original star selection and optimization process.

Starcheck should also be doing all the proseco parameter validation checks in any case as well to generate a critical warning if there is a mismatch (indicating a real problem somewhere in the system).  So the downsides you mentioned are going to happen in any case, but I do see the value in "independently" evaluating the to-be-run catalogs.  With quotes there because of course it is the same tool with the same bugs.

**Comment by jeanconn** [comment]
> Another option that might be reasonable is effectively re-running proseco but forcing it to use the backstop catalog and other inputs and turning off optimization. This will give you the marginalized p_acq values for exactly the to-be-flown backstop and should do the right thing for edited catalogs.

I think this might be the same as what I was suggesting.  But will refine as we get there.
