### ISSUE TITLE
Is an exception on get_aca_catalog being handled such that get_review_table is not called?

### ISSUE THREAD

**Issue by jeanconn** [sot/proseco#302]
Is an exception from get_aca_catalog being handled such that get_review_table is not called on an empty/errored catalog?   

Based on seeing PYPROC error messages like

```
PYPROC: <class 'KeyError'>: ('yang',)
PYPROC: Traceback (most recent call last):
PYPROC:   File "<string>", line 1, in <module>
PYPROC:   File "<string>", line 22, in <module>
PYPROC:   File "/proj/sot/ska3/matlab32/flight/lib/python3.6/site-packages/proseco/catalog.py", line 246, in get_review_table
PYPROC:     return ACAReviewTable(self)
PYPROC:   File "/proj/sot/ska3/matlab32/flight/lib/python3.6/site-packages/sparkles/core.py", line 371, in __init__
PYPROC:     self.add_row_col()
PYPROC:   File "/proj/sot/ska3/matlab32/flight/lib/python3.6/site-packages/sparkles/core.py", line 716, in add_row_col
PYPROC:     row, col = yagzag_to_pixels(self['yang'], self['zang'], allow_bad=True)
PYPROC:   File "/proj/sot/ska3/matlab32/flight/lib/python3.6/site-packages/astropy/table/table.py", line 1222, in __getitem__
PYPROC:     return self.columns[item]
PYPROC:   File "/proj/sot/ska3/matlab32/flight/lib/python3.6/site-packages/astropy/table/table.py", line 106, in __getitem__
PYPROC:     return OrderedDict.__getitem__(self, item)
PYPROC: Error executing python statement: 'exec(Path(MX_VAR_doWorkFile).open().read())' - ('yang',)
```

I am guessing that get_review_table is still being called if there is an empty catalog that doesn't have the 'yang' column.  I can get a similar traceback directly.

```
In [5]: cat = proseco.get_aca_catalog(obsid=1, raise_exc=False)
c
In [6]: cat.get_review_table()
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-5b328709e666> in <module>()
----> 1 cat.get_review_table()

/proj/sot/ska3/matlab32/flight/lib/python3.6/site-packages/proseco/catalog.py in get_review_table(self)
    244         from sparkles.core import ACAReviewTable
    245 
--> 246         return ACAReviewTable(self)
    247 
    248     def get_candidates_mask(self, stars):

/proj/sot/ska3/matlab32/flight/lib/python3.6/site-packages/sparkles/core.py in __init__(self, *args, **kwargs)
    369 
    370         # Add row and col columns from yag/zag, if not already there.
--> 371         self.add_row_col()
    372 
    373         self.context = {}  # Jinja2 context for output HTML review

/proj/sot/ska3/matlab32/flight/lib/python3.6/site-packages/sparkles/core.py in add_row_col(self)
    714             return
    715 
--> 716         row, col = yagzag_to_pixels(self['yang'], self['zang'], allow_bad=True)
    717         index = self.colnames.index('zang') + 1
    718         self.add_column(Column(row, name='row'), index=index)

/proj/sot/ska3/matlab32/flight/lib/python3.6/site-packages/astropy/table/table.py in __getitem__(self, item)
   1220     def __getitem__(self, item):
   1221         if isinstance(item, str):
-> 1222             return self.columns[item]
   1223         elif isinstance(item, (int, np.integer)):
   1224             return self.Row(self, item)

/proj/sot/ska3/matlab32/flight/lib/python3.6/site-packages/astropy/table/table.py in __getitem__(self, item)
    104         """
    105         if isinstance(item, str):
--> 106             return OrderedDict.__getitem__(self, item)
    107         elif isinstance(item, (int, np.integer)):
    108             return self.values()[item]

KeyError: 'yang'
```

This suggests to me that the empty/errored catalog should be handled either on the proseco/sparkles side (via a change to get_review_table) or on the ORViewer side such that get_review_table is not called for an empty/errored table.  @taldcroft suggests the ORViewer side.

**Comment by taldcroft** [comment]
*I think* that we have it correct right now.  My understanding is that we do not want to *ever* have an unhandled Python exception in a MATLAB pyexec call.  That was the design, in which case we are doing the right thing by having proseco (carefully) do the exception handling and ensuring that one never gets raised to pyexec.

Then MATLAB is responsible for checking the output (in particular the `exception` attribute) and proceeding accordingly.  Thats the API.  ORviewer is responsible for not calling `get_review_table` if there was an exception.

**Comment by jeanconn** [comment]
@jskrist regarding "ORviewer is responsible for not calling get_review_table if there was an exception." is that happening? I got lost about where the code is to check myself.

**Comment by jeanconn** [comment]
This came up via @mbaski sending me a traceback from Matlab / PYPROC that looked basically exactly like the one I included above while were were configuring a new ska environment to work with BUOCC matlab installs.

**Comment by taldcroft** [comment]
OK, that bit of context is important and was not clear from the original message.  Without knowing quite enough, I'd call that a bug in ORviewer.  The API is that exceptions are *possible* in proseco and need to be handled in MATLAB.

**Comment by jeanconn** [comment]
Good point that the `exception` attribute should be handled somewhere so there's no need to consider setting raise_exc=True on the get_aca_catalog call.

**Comment by jeanconn** [comment]
Also I've updated the original issue text.  I disagree a bit on implementation and think that perhaps get_review_table should do something like making an "empty table and see exception" message and capturing the exception, so the recommended Python API can be simple on both sides.

**Comment by taldcroft** [comment]
Fair enough that the current sparkles code has exception handling in the "main" interface (`run_aca_review` at the module level) but doesn't do any input validation in the `ACAReviewTable` init.  

So up-front checking for an empty table and checking for an exception on the `ACATable` object would be grounds to raise an exception with an informative message.  Both of those should never happen, but if they do because of an upstream code error then we should make that easier to diagnose.

**Comment by jskrist** [comment]
@jeanconn thanks for the discussion.  Sorry for the slow response.  It looks like there is no error check in the python script being called from the MATLAB tools at the moment:

```
  # create acaTable
  aca = get_aca_catalog(**kw_dict)
  acas_dict[obsid] = aca
  # get acaReviewTable
  acar = aca.get_review_table()
  acars_dict[obsid] = acar
```
The code is setting the `raise_exc` key to `False`.  Will proseco still fill the `exception` attribute in this case?  I haven't seen `exception` be anything other than an empty string, but I also don't have inputs to reproduce the error mentioned here.

I have gone through the relevant code and put in conditional checks to handle the case where get_aca_catalog() returns an object with a non-empty `exception` attribute.  I may ask @jeanconn or @taldcroft to review the code changes at some point (it looks clunky to me), but it will likely only be available from an SVN branch.  I think it might be simpler to handle this issue if the API returned an empty table with an appropriate message in the `exception` attribute, as @jeanconn suggested.

**Comment by jeanconn** [comment]
I think this is now handled on the matlab side, but I'm still not sure if we want get_review_table to throw the exception.

**Comment by taldcroft** [comment]
This specific issue is closed.  I don't see a real need to open any other issue regarding exception handling, things seem to be working.
