### ISSUE TITLE
MATLAB should rely entirely on proseco catalog for uplinked catalog values

### ISSUE THREAD

**Issue by jeanconn** [sot/proseco#304]
This includes in particular MAXMAG DIM RES HALFW, and relates to #305

**Comment by jeanconn** [comment]
Related to https://github.com/sot/ska-projects/issues/38

**Comment by taldcroft** [comment]
I changed the title to reflect that `maxmag` is already available to ORviewer, it just chooses to ignore it right now.  This would require no change to proseco (unless we independently decide to tweak ow maxmag is computed).

**Comment by jeanconn** [comment]
Thanks!  I agree "pass" was ambiguous.

**Comment by jeanconn** [comment]
Should we broaden this issue to mention the other things we probably want on the Matlab side for #305 ?  Or close this issue as already delegated to FOT?

**Comment by taldcroft** [comment]
Broaden.  I changed the title and description.

**Comment by jeanconn** [comment]
Might need 'type' too; I can't remember if the Matlab code is still working with the lower-level tables directly.

**Comment by taldcroft** [comment]
I assume that ORviewer is already using TYPE and that it does not deal with the low-level tables directly.

**Comment by jskrist** [comment]
The MATLAB code is currently utilizing the aca.acqs, aca.guides, and aca.fids directly, instead of using the ```type``` field.  Let me know if this is not a supported workflow and I can update the code.
Also, I have been looking through the values available from proseco and those that are currently calculated in MATLAB.  Some fields map directly or need a simple unit conversion, but there are other fields I am not sure about, e.g. MATLAB stores a magMin value, but this is not directly available from the ACATable as far as I can tell and I'd like to make sure I am calculating these values as accurately as possible.

**Comment by jeanconn** [comment]
Do the elements of this have jira tickets and do you have a plan for which release the changes could end up in @jskrist?

**Comment by jskrist** [comment]
I created a new ticket for this in JIRA, [MATLAB-11602](https://occ-cfa.cfa.harvard.edu/browse/MATLAB-11602).  There is no consensus yet on a release, but I am not currently opposed to putting it in the 2020_010 release.  We have a MATLAB Tools Development Group meeting in an hour though, and can discuss it more there.

**Comment by jeanconn** [comment]
This is big enough we may need a more comprehensive / explicit test plan (which for the FOT probably just means more than one test schedule supplied to ACA).

**Comment by jeanconn** [comment]
> The MATLAB code is currently utilizing the aca.acqs, aca.guides, and aca.fids directly, instead of using the `type` field. Let me know if this is not a supported workflow and I can update the code.
> Also, I have been looking through the values available from proseco and those that are currently calculated in MATLAB. Some fields map directly or need a simple unit conversion, but there are other fields I am not sure about, e.g. MATLAB stores a magMin value, but this is not directly available from the ACATable as far as I can tell and I'd like to make sure I am calculating these values as accurately as possible.

**Comment by taldcroft** [comment]
Closing this here since this is done in MATLAB dev code and the proseco bit is done. Tracking here is not helping us.
