### ISSUE TITLE
Add 'dark' kwarg to api docstring for get_aca_catalog

### ISSUE THREAD

**Issue by jeanconn** [sot/proseco#313]
Add 'dark' kwarg to api docstring for get_aca_catalog

**Comment by taldcroft** [comment]
It would be almost as fast to just do the PR...

**Comment by taldcroft** [comment]
.. from GitHub.

**Comment by jeanconn** [comment]
Yeah, but I didn't quite understand how it worked so I didn't want to update the docs without walking through it.
