### ISSUE TITLE
Use a supplied penalty limit from the MATLAB side

### ISSUE THREAD

**Issue by jeanconn** [sot/proseco#318]
Use a supplied penalty limit from the MATLAB side.

If we use a supplied aca penalty limit temperature from the MATLAB side we could perhaps update the ACA limits without a Ska/proseco code change.  However, since it is possible we'll want to change the effective temperature calculation, acquisition model, or other piece of code due to a limit change, this issue/change is unlikely to buy us much (hence the low priority).

**Comment by taldcroft** [comment]
The API to allow this is included in #365. I'm going to close this, as either MATLAB will do it or the limit will be pulled from chandra_models. In any case it is out of our hands.
