### ISSUE TITLE
Avoid bona fide bad pixels and bad stars

### ISSUE THREAD

**Issue by taldcroft** [sot/proseco#34]
There are some actual bad (not just hot) pixels / bad pixel regions that should be avoided.

This applies to fid, guide and acq selection.

**Comment by jeanconn** [comment]
I know about the big trap, and about a little trap to avoid for fid selection.   Do we have some other bad pixels hanging around?  And should we define ones that are over some TDB threshold as "bad" not just hot?

**Comment by jeanconn** [comment]
Is this just for fid and guide or do we need to avoid bad pixels in the search box?

**Comment by taldcroft** [comment]
Plan for 4.0 is to avoid bad pixels in the acq search box (make p_acq be 0.0 if a bad pixel is in the box).  

Could later be refined to reflect a fractional probability update based on presence of a bad pixel in the box.

**Comment by taldcroft** [comment]
> And should we define ones that are over some TDB threshold as "bad" not just hot?

Definitely not for acq.  The design philosophy in proseco is to use the actual dark map, so even a "super-hot" pixel should be handled in that way.

**Comment by jeanconn** [comment]
I think this might need a new issue; we should review acq performance near the bad column / trap and/or do some test acquisitions there.  It ends up being a big region for excluding acq stars.
