### ISSUE TITLE
Investigate one-shot distribution over last several years.

### ISSUE THREAD

**Issue by taldcroft** [sot/proseco#4]
There needs to be careful justification of the typical small-box search window size.  Right now it is set arbitrarily at 60 arcsec.

**Comment by jeanconn** [comment]
For the distribution, is review as simple as looking at something like this?

http://nbviewer.jupyter.org/url/cxc.harvard.edu/mta/ASPECT/ipynb/box_one_shots.ipynb

**Comment by taldcroft** [comment]
Yes, that looks right on target, thanks!  The 1% wag on P_big looks about right.  Only comments:
- P_big should be between 60 and 120 arcsec (though I'm sure you had a reason for 80 - 140 but I don't see it).
- You might be able to make another version of the plot that allows reading the relevant values straight from the plot.  Namely a cumulative plot for x > N (`cumulative=-1, normed=True, log=True`  ?)  So that should show about 0.007 at 80.  Of course this is adding P_anomalous to P_big, but that's a small effect.
- Another sensible date filter is after the Kalman limit threshold patch.  That probably reduced the frequency of big one-shots (and certainly anomalous).
- I just looked and 18265 was *before* the patch.  :tada:  In fact that is one of the famous near-miss observations (from Mar 14) that got us cracking on big boxes.

**Comment by jeanconn** [comment]
> P_big should be between 60 and 120 arcsec (though I'm sure you had a reason for 80 - 140 but I don't see it).

I took a stab at it based on the 80, 100, 120 P_bigs I saw in acq.py, but that was implicit not explicit.

> You might be able to make another version of the plot that allows reading the relevant values straight from the plot. Namely a cumulative plot for x > N (cumulative=-1, normed=True, log=True ?) So that should show about 0.007 at 80. 

I figured and will do this.  

> Of course this is adding P_anomalous to P_big, but that's a small effect.

Though it looks like the really anomalous ones aren't in kadi (no defined one_shot maybe) so there aren't any with > 140.

> I just looked and 18265 was before the patch. 🎉 In fact that is one of the famous near-miss observations (from Mar 14) that got us cracking on big boxes.

Yep, though I couldn't recall if we had decided the one shot there was due to roll error (improved by Kalman limit patch) or due to bias jump.

**Comment by taldcroft** [comment]
Closed #12 and
http://nbviewer.jupyter.org/url/cxc.cfa.harvard.edu/mta/ASPECT/ipynb/star_selection/proseco-man-err-distribution.ipynb
