### ISSUE TITLE
Provide CCD temperature at time of acquisition and max during observation

### ISSUE THREAD

**Issue by taldcroft** [sot/proseco#46]
Define and implement a mechanism / data structure to pass the ACA CCD temperature from FOT Matlab tools to relevant proseco functions.

- For acq / fid selection this should be the CCD temperature at the time of acquisition
- For guide selection this should be the max CCD temperature during the observation

**Comment by jeanconn** [comment]
I've done this by putting both in the "AxafState" data structure used in the tools.  Now I will just need to find out from the FOT if this breaks things that aren't star selection.

**Comment by jeanconn** [comment]
Also, are our private repos private enough to put a repo of the tools up for this project?  I started to do so and then wasn't sure.

**Comment by jeanconn** [comment]
Also, for me the bigger deal wrt to API is trying to figure out how and where to save out your report yaml in a reasonable way.

**Comment by jeanconn** [comment]
For this, the implementation is already there in the matlab tools for 4.0

Then, I think we actually just need to decide what makes sense as an integration test to show that the matlab tools supplied temperatures are reasonable compared to an independent run of the aca thermal model (maybe all in starcheck?).  I think that can be a 4.1 test release item.

**Comment by taldcroft** [comment]
Seems like most of the machinery is already there in starcheck, so I would suggest that this test (both for development testing and in regular load review) be done there.

**Comment by taldcroft** [comment]
Done in Matlab, will open a test issue.
