### ISSUE TITLE
Fid selection breaks on obsids 20144 and 19605

### ISSUE THREAD

**Issue by jeanconn** [sot/proseco#54]
So far, the example in testing (19387) is the only one I can get to work.  The rest I try seem to fail with this.

```
In [9]: acqs = proseco.acq.AcqTable.get_acq_catalog(18680)

In [10]: fids = proseco.fid.get_fid_catalog(detector='ACIS-S', acqs=acqs)

...
/fido.real/skare3/lib/python3.6/site-packages/astropy/table/table.py in _init_from_cols(self, cols)
    752         if len(lengths) != 1:
    753             raise ValueError('Inconsistent data column lengths: {0}'
--> 754                              .format(lengths))
    755 
    756         # Set the table masking

ValueError: Inconsistent data column lengths: {0, 1}
```

**Comment by jeanconn** [comment]
I suppose 18680 was actually an HRC-S observation, and that seems to work.  Should the fid selection come up with something for each detector anyway?
  
Here are some more 'true' examples (actual detector for obsid)
```
In [51]: acqs = proseco.acq.AcqTable.get_acq_catalog(20144)
In [52]: fids = proseco.fid.get_fid_catalog(detector='ACIS-I', acqs=acqs)
...   
 934     def _make_compare(oper):
ValueError: could not broadcast input array from shape (2) into shape (1)
```

```
In [62]: acqs = proseco.acq.AcqTable.get_acq_catalog(19605)
In [63]: fids = proseco.fid.get_fid_catalog(detector='ACIS-S', acqs=acqs)    756         
...
# Set the table masking
ValueError: Inconsistent data column lengths: {0, 1}
```

**Comment by taldcroft** [comment]
Thanks.  Probably best to hold off on testing at this point until I get further along.  As per acq, I will run this on 8-10 weekly schedules and that would presumably pick up issues like this.

**Comment by jeanconn** [comment]
Right, which is also why I was asking about the status of master.  I was, however, just trying to see what inputs we need to consider API for matlab, which is how I got here.

**Comment by jeanconn** [comment]
I don't disagree.  But since I didn't have that master method handy, I was just starting with trying to call the fid selection directly to look at the data structures to see what we need to paste back into the SAUSAGE data structures.

**Comment by jeanconn** [comment]
I was also looking at prototyping that master method for testing, but don't know if you already have that done somewhere.
