### ISSUE TITLE
Fid selection should watch out for spoiler stars in the fid box with (guide phase) dither

### ISSUE THREAD

**Issue by jeanconn** [sot/proseco#55]

**Comment by taldcroft** [comment]
I think this is done, but am I misinterpreting??  Note that the code in master at this point does not include *using* the spoiler score to co-optimize fid and acq catalogs.  See [page 21 - 29](https://docs.google.com/presentation/d/1j89Zy2RRB4McV32ue-EpQThaEpiONw_EAilqcOqz45g/edit#slide=id.gc8be552d7_0_0)

https://github.com/sot/proseco/blob/977466d787a3e25b4b0e24741191f469d88d659c/proseco/fid.py#L302

**Comment by taldcroft** [comment]
OK, I put in #56 now.  Can this issue be closed?
