### ISSUE TITLE
Use dither_y and dither_z by acq phase and guide phase throughout

### ISSUE THREAD

**Issue by taldcroft** [sot/proseco#56]
Scrub all acq, guide, and fid selection to ensure proper use of two-component dither.

**Comment by taldcroft** [comment]
At the least the acq and fid interfaces need to accept a two-element list for 1.0.

**Comment by jeanconn** [comment]
I think for 1.0 we just need to take the two-element list at get_aca_catalog(), but it would be great to also have them supported in get_acq/get_fid.

**Comment by taldcroft** [comment]
> I think for 1.0 we just need to take the two-element list at get_aca_catalog(), but it would be great to also have them supported in get_acq/get_fid.

This is done for 1.0 with #77, so re-milestoning for 4.0.
