### ISSUE TITLE
Need to define new requirements for when to convert MON to GUI

### ISSUE THREAD

**Issue by jeanconn** [sot/proseco#65]
The current mission planning guideline is that a monitor star should be converted to a guide star if the star is brighter than or equal to 10.5 and if the star would be selected by SAUSAGE as a ACQ in stage 3 or better.

SSAWG should pick a new rule soon. 10.5 is outdated and ACQ won't have stages.
We'll try to implement the new rule via proseco code (submit mon request, get guide back) or it may still be manual.

**Comment by taldcroft** [comment]
Sorry, I need some help here.  Context?  Is this needed for 4.0?

**Comment by taldcroft** [comment]
What about a new rule for manual use with proseco 4.0:

*Monitor star should be converted to a guide star if it is picked by proseco or at the discretion of the ACA reviewer.*

I don't think we should have auto mon star selection in 4.0.

**Comment by jeanconn** [comment]
I assume you mean "if it is picked by proseco as a guide star"?  

You'd suggested auto selection of the DTS which will also need some kind of recommendation.  Is the brightest thing the best? or is the brightest thing in the first stage (which should be least spoiled) the better choice?

**Comment by taldcroft** [comment]
Yes on it being picked as a guide star.  I think just the brightest mag is fine, consistent with current process by FOT MP.  Don't they manually select the DTS now?  Or is that SAUSAGE?

Goal now is to minimize footprint of changes to code and process.
