### ISSUE TITLE
Investigate updating backstop products to inject proseco catalogs into loads

### ISSUE THREAD

**Issue by taldcroft** [sot/proseco#7]
It would be a really good thing to be able to evaluate proseco catalogs with starcheck.

I think this is not conceptually difficult.  At least the DOT, backstop, and guide summary files need updating.  Any more?  Getting all the details right is the trick.  SAUSAGE does this, so worth checking that out to see if it provides any guidance.

**Comment by jeanconn** [comment]
Do you want this as a path to using proseco in operations or just for testing/evaluation?

**Comment by taldcroft** [comment]
Just for testing.

**Comment by taldcroft** [comment]
Done in the latest chandra_aca.
