### ISSUE TITLE
Can't pickle weakref objects

### ISSUE THREAD

**Issue by jeanconn** [sot/proseco#73]
So, what do we win with the weakrefs?  Ended up with this on my first go.

```
----> 1 catalog.to_pickle()

/proj/sot/ska/jeanproj/git/proseco/proseco/core.py in to_pickle(self, rootdir)
    193         outfile = outdir / f'{self.name}.pkl'
    194         with open(outfile, 'wb') as fh:
--> 195             pickle.dump(self, fh)
    196 
    197     @classmethod

TypeError: can't pickle weakref objects
```

**Comment by taldcroft** [comment]
Using direct refs looks to be fine.  For 4.0 release we will need to confirm (empirically) that we don't get a memory leak from uncollected circular refs.  For now, closing this as overtaken by code and #76.
