### ISSUE TITLE
Use traceback to capture exception stack trace

### ISSUE THREAD

**Issue by taldcroft** [sot/proseco#74]
In the ACA catalog object, there should be code like below to catch any exception.  Then the traceback should be put into `meta['exception']`.  This will wind up in the pickle and can be examined by the developers.

```
In [30]: import traceback
In [31]: try:
    ...:     1/0
    ...: except Exception:
    ...:     print(traceback.format_exc())
    ...:     
Traceback (most recent call last):
  File "<ipython-input-31-d18bde6b97c4>", line 2, in <module>
    1/0
ZeroDivisionError: division by zero
```
Milestoned for 1.0 to help us debug anything weird that comes up.

**Comment by jeanconn** [comment]
I'm a little confused about interface.  Right now I'm calling get_aca_catalog and building an ACA catalog table as part of that method.  Where do I put exception handling *in* the object?  I thought I'd have exception handling in the method or in the lower methods (wrappers for get_acq_catalog etc).

**Comment by taldcroft** [comment]
It should just be roughly:
```
def get_aca_catalog(**kwargs):
    try:
        aca = _get_aca_catalog(**kwargs)
    except Exception:
        aca = ACACatalogTable.empty()  # Makes zero-length table with correct columns
        aca.meta['exception'] = traceback.format_exc()
    return aca

def _get_aca_catalog(**kwargs):
    # Does the real work
```
There is no "catch-anything" exception handling in any lower level classes or methods.

**Comment by taldcroft** [comment]
Oops, mistake, stand by.

**Comment by taldcroft** [comment]
Updated with what I think it right.

**Comment by jeanconn** [comment]
Also, I think it is easy for me to unpack this on the matlab side if aca.acqs, aca.guides, and aca.fids are the things that have zero length in a failure case (and I thought they could be independently empty), but I'll review where we'd need conditionals

**Comment by jeanconn** [comment]
Oh, and that's the way you went with your edits.  OK.

**Comment by jeanconn** [comment]
Also, is that exactly the interface you want for get_aca_catalog?  I was still calling out keyword arguments by name because I figured it was the right thing on a public method, but I don't recall if there is a way to stick all the explicit keyword args into kwargs to pass to the private method at that point.

**Comment by taldcroft** [comment]
Yes, new method.  (I had typed this into the comment block before noticing my mistake and didn't get back to it).

Columns matter because downstream apps expect the table to have certain columns.  That's part of the API.  Also, as we know now, a table with no columns can't be pickled.

**Comment by taldcroft** [comment]
About **kwargs, that was shorthand.  We may want to go there at some point, but don't have to decide now.  It's OK for a public method to just use **kwargs as long as the actual available args are documented correct and the code does validation of what it gets.

BTW, it should probably be (in case of failure):
```
aca.acqs = AcqTable.empty(**kwargs)
```
The `empty()` method would fill in `meta` as best it can.

**Comment by jeanconn** [comment]
On the matlab side, I figured zero length would be fine to start (probably the thing we can most easily check anyway), so I just stubbed that in.

**Comment by jeanconn** [comment]
Yes, that sounds good.  Right now I'd been handling empty etc with extra lines of code, but your idea is better.
