### ISSUE TITLE
Anything else for 1.0?

### ISSUE THREAD

**Issue by taldcroft** [sot/proseco#82]
I pushed the milestone for #59 to 4.0 (though it should be done reasonably soon).  That leaves only #81 as on the list for the 1.0 milestone.  #81 is pretty straightforward and should be mergeable with minimal review.

So, anything else?  

I was wondering if we need the ability to trigger expected warnings or some exceptions.  As a weird idea, one could put a back-door in the code that watches for a particular attitude (within a few arcsec) and raises an exception.  (Just thinking of ways to do this without actually messing with the API nor requiring any special code in Matlab).

**Comment by taldcroft** [comment]
I think that's in core.py from #64.

**Comment by jeanconn** [comment]
Ah, OK, so there's now a warnings attribute/property with the list of warnings.  So that seems done for 1.0.  Not sure if we need the warnings on the matlab side but that's not a proseco issue.

**Comment by jeanconn** [comment]
Regarding 1.0 in general, I haven't had a chance to run the code from the matlab side specifying include_ids, exclude_ids, and halfwidths. From our own tests on the Python side that should be fine (but I always prefer to actually have *done it* as the fundamental evaluation on if the API spec is complete).

**Comment by taldcroft** [comment]
I thought the final disposition on manual catalog edits was that we basically ignore them, e.g. when calling proseco for writing the pickle file.  So the include and exclude are not needed even for 4.0 for Matlab.

**Comment by jeanconn** [comment]
I thought with regard to https://github.com/sot/proseco/issues/50#issuecomment-420413573 that for writing out the proseco file, I'd have the code check each catalog on the matlab side and use include and exclude ids if manually edited.  I didn't get the impression from that discussion that you wanted to defer that past 4.0 if possible.

I also think it is doable for 4.0, but of course will finish on the matlab side first with writing out the "what proseco would have done".

**Comment by jeanconn** [comment]
So, probably just a disagreement on what "requirement" means there.  

I thought, get it in if we have time and it works.  Since I'll be finishing up the file writing anyway, it seems not too much extra.  I wasn't sure that we'd backed away from having the pkl file itself as a 4.0 requirement (using 4.0 loosely to describe the final configured code that will be a combination of matlab and proseco ).

**Comment by jeanconn** [comment]
And looking back on that thread, I guess it wasn't a disagreement on requirements anyway, I'd just forgotten that I'd said "Sounds good" to the plan of not trying to get the include/exclude stuff in.

**Comment by taldcroft** [comment]
Also remember that every new feature, even if it just takes a short amount of time to implement, needs to be tested.  That means John Scott needs to have a test sheet that demonstrates hand-editing a catalog and then we verify that the output pickle file is correct.  That's why I want to push past 4.0 on this as something that isn't obviously *required*.  We have a perfectly good path forward without it that I'm quite comfortable with.

**Comment by taldcroft** [comment]
Sounds like the answer for 1.0 is that we are done.

**Comment by taldcroft** [comment]
Oops, except making a tag.  From my perspective we are ready, but I'll wait for @jeanconn to agree and do the tag.
